name: Enforce QA label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "qa-approved"
        REQUIRED_LABELS_ANY_DESCRIPTION: "PR is missing QA approval"
        BANNED_LABELS: "banned"
